import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ChevronDown,Command,LineChart,Bell,Brain,ShieldCheck,Users,WalletCards,Zap} from 'lucide-react';
import './styles.css';
import './marketing-motion.css';
import './privacy.css';
import './kitsetups-native-landing.css';
import PrivacyPolicy from './PrivacyPolicy';

const APP_URL='https://kitsetups.xyz';
const X_URL='https://x.com/kitsetups';
const BRAND='KitSetups';
const features=[
 {icon:Brain,title:'Trading command center',text:'Move from a market question to analysis, alerts and a clear next action without opening five different tools.'},
 {icon:LineChart,title:'Market view',text:'Track price structure, momentum and market-moving events from one focused workspace.'},
 {icon:Bell,title:'Alerts that matter',text:'Know when the conditions you care about change, without filling your screen with noise.'},
 {icon:WalletCards,title:'CEX, connected',text:'Bring your exchange workflow into the same place you use to research and monitor the market.'},
 {icon:ShieldCheck,title:'You stay in control',text:'Sensitive actions are built around permissions, confirmation and visible execution states.'},
 {icon:Zap,title:'Less friction',text:'Keep the path from an idea to an informed action short, clear and easy to follow.'}
];
const steps=[['01','Connect','Bring your trading environment into KitSetups.'],['02','Ask','Tell KitSetups what you want to understand or check.'],['03','Review','See the market context, signal and execution details.'],['04','Act','Execute with control — or keep monitoring.']];
function appLink(ref=''){return `${APP_URL}${ref?`/?ref=${encodeURIComponent(ref)}`:''}`}
function App(){const [open,setOpen]=useState(null);const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [ref,setRef]=useState('');const [copied,setCopied]=useState(false);
useEffect(()=>{try{const incoming=new URLSearchParams(window.location.search).get('ref')?.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,24);const saved=localStorage.getItem('kitsetups_referral_code')||localStorage.getItem('kitsetuop_referral_code')||localStorage.getItem('kitagent_referral_code')||'';if(incoming)localStorage.setItem('kitsetups_referral_code',incoming);setRef(incoming||saved)}catch{}},[]);
useEffect(()=>{const nodes=[...document.querySelectorAll('.reveal,.scrollSlide')];if(!('IntersectionObserver' in window)){nodes.forEach(n=>n.classList.add('is-visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.14,rootMargin:'0px 0px -8% 0px'});nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);
const referralLink=ref?appLink(ref):APP_URL;
const copyReferral=async()=>{if(!ref)return;try{await navigator.clipboard?.writeText(referralLink);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
return <div className="app">
<header><a className="brand" href="#top"><span className="brandMark"><Command size={18}/></span><span>{BRAND}</span></a><nav><a href="#features">Product</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="#affiliate">Affiliate</a></nav><div className="navActions"><a className="socialLink" href={X_URL} target="_blank" rel="noreferrer" aria-label="KitSetups on X">X</a><a className="login" href={referralLink}>Open app</a><a className="primary small" href={referralLink}>Launch {BRAND} <ArrowUpRight size={15}/></a></div></header><main id="top">
<section className="hero"><div className="heroBackdrop"/><div className="orb orbA"/><div className="orb orbB"/><div className="eyebrow"><span className="pulse"/> MARKET • TRADING • EXECUTION</div><h1><span className="heroLine">Trade smarter.</span><span className="heroLine heroAccent">Move with context.</span></h1><p className="heroCopy">{BRAND} brings market analysis, alerts and exchange actions into one command center for crypto traders.</p><div className="heroCtas"><a className="primary heroPrimary" href={referralLink}><span>Start using {BRAND}</span><ArrowUpRight size={16}/></a><a className="ghost heroSecondary" href="#how"><span>See how it works</span><ArrowUpRight size={15}/></a></div><div className="heroMeta" aria-label="KitSetups capabilities"><div className="heroMetaTrack"><span className="metaBlue">Live market data</span><span className="metaCyan">Decision support</span><span className="metaViolet">Built for crypto</span><span className="metaGreen">Real-time signals</span><span className="metaAmber">CEX ready</span><span className="metaPink">Risk-aware execution</span><span className="metaBlue">Live market data</span><span className="metaCyan">Decision support</span><span className="metaViolet">Built for crypto</span></div></div></section>
<section className="terminalWrap reveal"><div className="terminal"><div className="terminalTop"><div className="dots"><b/><b/><b/></div><span>kitsetups / command</span><span className="live">LIVE</span></div><div className="terminalGrid"><div className="commandPanel"><small>COMMAND</small><div className="commandText">“Analyze BTC structure and tell me what changed.”</div><div className="thinking"><span/><span/><span/> {BRAND} is reading the market</div><div className="result"><div className="resultHead"><span>BTC / USDT</span><strong>Structure shift detected</strong></div><div className="chart"><div className="line l1"/><div className="line l2"/><div className="mark m1">BOS</div><div className="mark m2">↑</div></div><div className="stats"><div><small>PRICE</small><b>$104,820</b></div><div><small>BIAS</small><b> bullish</b></div><div><small>TIMEFRAME</small><b>15m</b></div></div></div></div><div className="sidePanel"><div><small>MARKET PULSE</small><b>12 pairs</b></div><div className="miniRow"><span>BTC</span><strong>+2.84%</strong></div><div className="miniRow"><span>ETH</span><strong>+1.72%</strong></div><div className="miniRow"><span>SOL</span><strong>+4.08%</strong></div><div className="alertCard"><Bell size={15}/><span>High-impact event<br/><b>in 18 minutes</b></span></div></div></div></div></section>