import React from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,BrainCircuit,Check,ChevronRight,Command,Radar,ShieldCheck,Sparkles} from 'lucide-react';
import './styles.css';import './privacy.css';import PrivacyPolicy from './PrivacyPolicy';
const APP_URL='https://kitsetups.xyz',X_URL='https://x.com/kitsetups';
const rows=[['01','READ','Understand structure and market context.'],['02','QUALIFY','Wait for the conditions that make the idea valid.'],['03','DEFINE','Know entry, invalidation, target and risk.'],['04','ACT','Execute or keep the opportunity on watch.']];
function App(){return <div className="landing"><header className="nav"><a className="logo" href="#top"><span><Command size={16}/></span>KitSetups</a><nav><a href="#intelligence">Intelligence</a><a href="#workflow">Workflow</a><a href="#pricing">Pricing</a></nav><div className="navRight"><a className="xLink" href={X_URL} target="_blank" rel="noreferrer">X</a><a className="login" href={APP_URL}>Open app</a><a className="navCta" href={APP_URL}>Launch <ArrowUpRight size={14}/></a></div></header><main id="top">
<section className="hero"><div className="heroLeft"><div className="eyebrow"><i/> MARKET INTELLIGENCE / TRADING SYSTEM</div><h1>Trade with<br/><em>context.</em></h1><p className="heroLead">KitSetups turns market structure, price action, signals and risk into one clear trading workspace — built to help you see the setup before you make the move.</p><div className="heroActions"><a className="primary" href={APP_URL}>Enter KitSetups <ArrowUpRight size={16}/></a><a className="secondary" href="#intelligence">See the system <ChevronRight size={15}/></a></div><div className="heroMeta"><span><Check size={13}/> Market structure</span><span><Check size={13}/> Risk-aware setups</span><span><Check size={13}/> Connected execution</span></div></div>
<div className="heroStage"><div className="stageGlow"/><div className="stageTop"><span>KT / MARKET INTELLIGENCE</span><b><i/> LIVE</b></div><div className="stageChart"><div className="chartGrid"/><svg viewBox="0 0 800 360" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#1cc9ff" stopOpacity=".28"/><stop offset="100%" stopColor="#1cc9ff" stopOpacity="0"/></linearGradient></defs><path d="M0 290 C55 285 60 240 110 255 S170 290 220 210 S280 240 330 170 S395 210 440 145 S500 180 555 105 S610 155 660 92 S720 125 800 52 L800 360 L0 360Z" fill="url(#area)"/><path d="M0 290 C55 285 60 240 110 255 S170 290 220 210 S280 240 330 170 S395 210 440 145 S500 180 555 105 S610 155 660 92 S720 125 800 52" fill="none" stroke="#35d2ff" strokeWidth="3"/><circle cx="660" cy="92" r="6" fill="#35d2ff"/></svg><div className="chartLabel"><span>BTC / USDT</span><b>+4.82%</b></div><div className="priceAxis"><span>72.4K</span><span>71.8K</span><span>71.2K</span><span>70.6K</span></div></div><div className="intelPanel"><div className="intelHeader"><span>SETUP INTELLIGENCE</span><strong>CONFIRMED</strong></div><div className="intelPair"><div><small>MARKET BIAS</small><b>BULLISH</b></div><div><small>EXECUTION</small><b>15M</b></div><div><small>RISK</small><b>1 : 2.8</b></div></div><div className="intelBar"><span/></div><div className="intelFoot"><span>Structure aligned</span><span>Liquidity active</span><span>Risk defined</span></div></div><div className="floatTag"><span className="pulse"/> MARKET PULSE <b>12 instruments</b></div></div></section>
<div className="ticker"><span>BUILT FOR TRADERS</span><i/> MARKET STRUCTURE <i/> PRICE ACTION <i/> LIQUIDITY <i/> SETUPS <i/> RISK <i/> EXECUTION</div>
<section id="intelligence" className="intelligence"><div className="sectionIntro"><div><small>01 / THE INTELLIGENCE LAYER</small><h2>Don't just see<br/><em>the chart.</em></h2></div><p>See what the chart is saying. KitSetups is designed around the decisions traders actually make: direction, timing, invalidation and risk.</p></div><div className="intelGrid"><article className="bigFeature"><div className="featureKicker"><Radar size={15}/> MARKET STRUCTURE</div><div className="structureVisual"><span className="line one"/><span className="line two"/><span className="line three"/><b>HH</b><b>HL</b><b>HH</b></div><div><h3>Direction before entry.</h3><p>Higher-timeframe context gives every setup a reason to exist.</p></div></article><article className="featureCard"><span className="number">02</span><BrainCircuit/><h3>Context, not noise.</h3><p>Combine price action, market events and relevant conditions into a readable view.</p><a href={APP_URL}>Explore intelligence <ArrowUpRight size={14}/></a></article><article className="featureCard accentCard"><span className="number">03</span><ShieldCheck/><h3>Risk is part of the setup.</h3><p>Entry, invalidation, targets and leverage belong together before action.</p><div className="riskReadout"><span>RISK / REWARD</span><b>1 : 2.8</b></div></article></div></section>
<section id="workflow" className="workflow"><div className="workflowVisual"><div className="workflowTop"><span>YOUR TRADING WORKFLOW</span><span>04 STEPS</span></div>{rows.map((s,i)=><div className={'flowRow '+(i===2?'active':'')} key={s[0]}><b>{s[0]}</b><div><strong>{s[1]}</strong><p>{s[2]}</p></div><ArrowUpRight size={15}/></div>)}</div><div className="workflowCopy"><small>02 / THE WORKFLOW</small><h2>From market<br/><em>to decision.</em></h2><p>One continuous process instead of a pile of tabs. KitSetups keeps the important context close to the moment it matters.</p><div className="quote"><Sparkles size={17}/><span>The goal is not more information. It is better information at the right moment.</span></div></div></section>
<section className="manifesto"><div><small>03 / WHY KITSETUPS</small><h2>Built for traders<br/><em>who want clarity.</em></h2></div><div className="manifestoStats"><div><b>01</b><span>Structure-first</span><p>Market direction is treated as a foundation, not decoration.</p></div><div><b>02</b><span>Risk-aware</span><p>Every actionable idea needs a defined invalidation and target.</p></div><div><b>03</b><span>Less noise</span><p>Clear states separate opportunities from moments that are not ready.</p></div></div></section>
<section id="pricing" className="pricing"><div><small>04 / ACCESS</small><h2>Start with the<br/><em>edge you need.</em></h2><p>Explore the core workspace, then unlock deeper intelligence and advanced workflows when you are ready.</p></div><div className="plans"><article><span>FREE</span><strong>$0</strong><p>Start exploring KitSetups.</p><ul><li>Core market workspace</li><li>Market overview</li><li>Essential tools</li></ul><a className="outline" href={APP_URL}>Get started <ArrowUpRight size={14}/></a></article><article className="premium"><label>PREMIUM</label><span>FOR SERIOUS TRADERS</span><strong>$20 <small>/ month</small></strong><p>More intelligence. More control.</p><ul><li>Advanced market workflows</li><li>Expanded intelligence</li><li>Premium monitoring</li><li>Advanced trading tools</li></ul><a className="primary" href={APP_URL}>Go Premium <ArrowUpRight size={14}/></a></article></div></section>
<section className="finalCta"><div className="ctaOrb"/><small>THE NEXT MOVE IS YOURS</small><h2>See the market.<br/><em>See the setup.</em></h2><a className="primary" href={APP_URL}>Open KitSetups <ArrowUpRight size={16}/></a></section></main>
<footer><div className="footerBrand"><a className="logo" href="#top"><span><Command size={16}/></span>KitSetups</a><p>Market intelligence and trading workflows, brought into focus.</p></div><div className="footerLinks"><a href="#intelligence">Intelligence</a><a href="#workflow">Workflow</a><a href="#pricing">Pricing</a><a href={X_URL} target="_blank" rel="noreferrer">X</a><a href="/privacy">Privacy</a><a href={APP_URL}>App</a></div><div className="footerBottom"><span>© 2026 KitSetups</span><span>Trading involves risk.</span></div></footer></div>}
const root=createRoot(document.getElementById('root'));root.render(window.location.pathname==='/privacy'?<PrivacyPolicy/>:<App/>);