import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ChevronDown,Command,LineChart,Bell,Brain,ShieldCheck,Users,WalletCards,Zap,Activity,Search,Check} from 'lucide-react';
import './styles.css';
import './privacy.css';
import PrivacyPolicy from './PrivacyPolicy';

const APP_URL='https://kitsetups.xyz';
const X_URL='https://x.com/kitsetups';
const BRAND='KitSetups';
const images={
 hero:'https://images.unsplash.com/photo-1742076553114-cfd4f27de46f?auto=format&fit=crop&w=1800&q=88',
 chart:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=86',
 workspace:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=86',
 laptop:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=86'
};
const features=[
 {icon:Brain,title:'Understand the market',text:'Turn price action, structure and market events into one readable view.'},
 {icon:LineChart,title:'See what changed',text:'Keep the important movement in context instead of chasing isolated candles.'},
 {icon:Bell,title:'Get the right alerts',text:'Surface the conditions that matter to your setup without constant noise.'},
 {icon:WalletCards,title:'Connect your workflow',text:'Keep research, monitoring and exchange actions close together.'},
 {icon:ShieldCheck,title:'Stay in control',text:'Sensitive actions remain visible, permissioned and confirmable.'},
 {icon:Zap,title:'Move with less friction',text:'Shorten the distance between a market idea and an informed decision.'}
];
const steps=[['01','Connect','Bring your trading environment into one place.'],['02','Ask','Ask what changed, what matters and what needs attention.'],['03','Review','Read the context, setup and risk before acting.'],['04','Act','Execute when ready, or keep the market under watch.']];
function appLink(ref=''){return `${APP_URL}${ref?`/?ref=${encodeURIComponent(ref)}`:''}`}
function App(){const [open,setOpen]=useState(null);const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [ref,setRef]=useState('');const [copied,setCopied]=useState(false);
useEffect(()=>{try{const incoming=new URLSearchParams(window.location.search).get('ref')?.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,24);const saved=localStorage.getItem('kitsetups_referral_code')||localStorage.getItem('kitsetuop_referral_code')||localStorage.getItem('kitagent_referral_code')||'';if(incoming)localStorage.setItem('kitsetups_referral_code',incoming);setRef(incoming||saved)}catch{}},[]);
const referralLink=ref?appLink(ref):APP_URL;
const copyReferral=async()=>{if(!ref)return;try{await navigator.clipboard?.writeText(referralLink);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
return <div className="site">
<header className="header"><a className="brand" href="#top"><span className="brandMark"><Command size={17}/></span><span>{BRAND}</span></a><nav><a href="#product">Product</a><a href="#workflow">How it works</a><a href="#pricing">Pricing</a></nav><div className="headerActions"><a className="headerX" href={X_URL} target="_blank" rel="noreferrer">X</a><a className="headerLogin" href={referralLink}>Open app</a><a className="button buttonSmall" href={referralLink}>Launch <ArrowUpRight size={14}/></a></div></header>
<main id="top">
<section className="heroNew">
<div className="heroCopyNew"><div className="eyebrow"><span/>MARKET INTELLIGENCE / TRADING WORKSPACE</div><h1>The market is noisy.<br/><em>Your decisions don't have to be.</em></h1><p>KitSetups brings analysis, market context, alerts and connected trading workflows into one focused command center.</p><div className="heroButtons"><a className="button" href={referralLink}>Open KitSetups <ArrowUpRight size={16}/></a><a className="textButton" href="#product">Explore the product <ArrowUpRight size={15}/></a></div><div className="heroProof"><span><Activity size={14}/> Live market context</span><span><Check size={14}/> Risk-aware workflow</span><span><Check size={14}/> CEX ready</span></div></div>
<div className="heroVisual"><img src={images.hero} alt="Trader working with a live market chart on a laptop"/><div className="imageShade"/><div className="visualLabel"><span>LIVE WORKSPACE</span><b>MARKET / 24H</b></div><div className="floatCard signal"><small>MARKET SIGNAL</small><strong>BTC / USDT</strong><div><b>Structure shift</b><span>+2.84%</span></div><i>Context confirmed</i></div><div className="floatCard pulseCard"><span className="pulseDot"/>MARKET PULSE <b>12 pairs</b></div></div>
</section>
<div className="ticker"><span>BUILT FOR CRYPTO TRADERS</span><i/> <span>MARKET DATA</span><i/> <span>ANALYSIS</span><i/> <span>ALERTS</span><i/> <span>EXECUTION</span><i/> <span>RISK CONTROL</span></div>
<section id="product" className="editorial">
<div className="sectionHead"><div><span className="kicker">THE PRODUCT</span><h2>One workspace.<br/><em>More signal.</em></h2></div><p>Stop stitching your trading process together across tabs. KitSetups gives every decision a place to land.</p></div>
<div className="photoGrid"><article className="photoLarge"><img src={images.chart} alt="Financial market chart on a laptop"/><div className="photoCaption"><span>01 / MARKET VIEW</span><strong>Read price, structure and momentum in context.</strong></div></article><article className="photoSmall"><img src={images.workspace} alt="Professional workspace"/><div className="photoCaption"><span>02 / FOCUSED WORKSPACE</span><strong>Keep the work clean and distraction-free.</strong></div></article><article className="photoSmall darkPanel"><div className="miniTerminal"><div className="miniTop"><span>kitsetups / analysis</span><b>LIVE</b></div><div className="miniSearch"><Search size={14}/> Analyze BTC structure</div><div className="miniRows"><span>Trend <b>BULLISH</b></span><span>Liquidity <b>ACTIVE</b></span><span>Event risk <b>LOW</b></span><span>Setup <b>QUALIFIED</b></span></div></div><div className="photoCaption"><span>03 / DECISION LAYER</span><strong>Context before action.</strong></div></article></div>
</section>
<section className="featureSection"><div className="sectionHead compact"><div><span className="kicker">WHY KITSETUPS</span><h2>Everything around<br/><em>the decision.</em></h2></div><p>Designed to make the trading process feel like one product, not six disconnected tools.</p></div><div className="featureList">{features.map((f,i)=><article key={f.title}><div className="featureNo">0{i+1}</div><div className="featureIcon"><f.icon size={18}/></div><div><h3>{f.title}</h3><p>{f.text}</p></div><ArrowUpRight className="featureArrow" size={18}/></article>)}</div></section>
<section id="workflow" className="workflow"><div className="workflowVisual"><img src={images.laptop} alt="Person working at a laptop in a modern workspace"/><div className="workflowOverlay"><div><small>YOUR WORKFLOW</small><strong>Question → Context → Decision</strong></div><span>04</span></div></div><div className="workflowCopy"><span className="kicker">HOW IT WORKS</span><h2>Less jumping.<br/><em>More thinking.</em></h2><p>KitSetups keeps the important parts of your process in sequence, so the interface gets out of the way.</p>{steps.map(s=><div className="stepRow" key={s[0]}><b>{s[0]}</b><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></section>
<section id="pricing" className="pricingNew"><div className="sectionHead compact"><div><span className="kicker">PRICING</span><h2>Start simple.<br/><em>Scale your edge.</em></h2></div><p>Use the core workspace free. Upgrade when you need deeper market intelligence and advanced workflows.</p></div><div className="plans"><article><span className="planLabel">FREE</span><h3>$0</h3><p>For exploring the command center.</p><ul><li>Core market assistance</li><li>Market overview</li><li>Basic alerts</li></ul><a className="outlineButton" href={referralLink}>Get started</a></article><article className="planPremium"><div className="premiumTag">PREMIUM</div><span className="planLabel">FOR SERIOUS USERS</span><h3>$20 <small>/ month</small></h3><p>More depth, monitoring and trading control.</p><ul><li>Advanced market workflows</li><li>Expanded market intelligence</li><li>Premium alerts & monitoring</li><li>Advanced trading tools</li></ul><a className="button" href={referralLink}>Go Premium <ArrowUpRight size={15}/></a></article></div></section>
<section id="affiliate" className="affiliateNew"><div><span className="kicker">AFFILIATE</span><h2>Turn your audience<br/><em>into recurring value.</em></h2><p>Share KitSetups with your community and earn <strong>10% recurring commission</strong> when referred users complete qualifying Premium payments.</p><div className="affiliateSteps"><span>Register</span><b>→</b><span>Share</span><b>→</b><span>Upgrade</span><b>→</b><strong>10% recurring</strong></div></div><div className="affiliateBox"><div className="boxHead"><span>REFERRAL CENTER</span><Users size={16}/></div><label>YOUR CODE</label><div className="codeRow"><input value={ref} onChange={e=>setRef(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''))} placeholder="Available after registration" readOnly={Boolean(ref)}/><button onClick={copyReferral}>{copied?'Copied':'Copy'}</button></div><a className="button full" href={`${APP_URL}/?auth=signup&affiliate=1`}>Register as affiliate <ArrowUpRight size={15}/></a><small>Monthly payout once your available balance reaches the $20 minimum.</small></div></section>
<section className="faqNew"><div className="faqTitle"><span className="kicker">FAQ</span><h2>Clear answers.<br/><em>No fine print maze.</em></h2></div><div>{[['What is KitSetups?',`${BRAND} is a trading command center combining market analysis, alerts and connected exchange workflows.`],['Does KitSetups execute trades?','The product is built around connected trading workflows and controlled execution. Sensitive actions remain permissioned and confirmable.'],['How does the affiliate programme work?',`Create an affiliate profile, receive your unique referral code and share it. Qualifying Premium payments from attributed users generate 10% recurring commission.`],['When do affiliates get paid?','Affiliate earnings are tracked in the dashboard and paid monthly once the available balance reaches the $20 minimum payout.']].map((x,i)=><div className="faqRow" key={i}><button onClick={()=>setOpen(open===i?null:i)}><span>{x[0]}</span><ChevronDown className={open===i?'open':''} size={18}/></button>{open===i&&<p>{x[1]}</p>}</div>)}</div></section>
<section className="newsletterNew"><div><span className="kicker">STAY IN THE LOOP</span><h2>The product keeps moving.<br/><em>Stay close.</em></h2></div><form onSubmit={e=>{e.preventDefault();if(email){setSent(true);setEmail('')}}}><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" required/><button className="button">{sent?'Subscribed':'Subscribe'} <ArrowUpRight size={15}/></button></form></section>
</main>
<footer><div className="footerTop"><div className="brand"><span className="brandMark"><Command size={16}/></span>{BRAND}</div><p>Market intelligence and trading workflows, brought into focus.</p><div className="footerLinks"><a href="#product">Product</a><a href="#pricing">Pricing</a><a href="#affiliate">Affiliate</a><a href={X_URL} target="_blank" rel="noreferrer">X</a><a href={referralLink}>App</a><a href="/privacy">Privacy</a></div></div><div className="footerBottom"><span>© 2026 {BRAND}</span><span>Trading involves risk.</span></div></footer>
</div>}
const root=createRoot(document.getElementById('root'));root.render(window.location.pathname==='/privacy'?<PrivacyPolicy/>:<App/>);